### ISSUE TITLE
[PHP] PHP comment highlighting closing tag issue

### ISSUE THREAD

**Issue by ncwalls** [sublimehq/Packages#3588] opened 2022-11-22 17:53 UTC
### What happened?

This used to work but broke in a recent update. (I'm on build 4143 but I think it was an update before this.)
In php when commenting out some code, if there is any php closing tag `?>`, it stops the comment coloring when it should go all the way until the comment closing tag `*/`.

```
<?php /*
  this code is the correct commented color
  <?php this code is the correct commented color  ?>
  this code goes back to regular coloring but should still be comment colored.
*/ ?>
```

**Comment by deathaxe** [comment] 2022-11-22 18:00
Duplicate of https://github.com/sublimehq/Packages/issues/3535 and https://github.com/sublimehq/Packages/issues/3540. Fixed by https://github.com/sublimehq/Packages/pull/3537.

**Closed** 2022-11-22 19:06 UTC
Labels: duplicate
