### ISSUE TITLE
 Djaneiro [Python]  Red equal sign in Django field attributes

### ISSUE THREAD

**Issue by diek** [sublimehq/Packages#3137] opened 2021-11-22 17:10 UTC
### What happened?

I am getting red background on equal sign, As far as I can see it is limited to models.py and model fields.  I have used Djaneiro for a long time without issue, I recently updated to Big Sur. I have tried contacting the Djaneiro maintainers to no avail.  No linting errors were reported, and I then disabled linting to check if that was the problem.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/1261158/142904751-e635f782-2733-48d2-a46a-188681643e52.png">

**Comment by michaelblyons** [comment] 2021-11-22 17:24
Can you please include the text as text in addition to the screenshot, and perhaps verify that you're using the shipped Python highlighting?

**Comment by deathaxe** [comment] 2021-11-22 17:47
May need some more context. I can't reproduce the issue with the provided code snippet on ST4122.

**Comment by deathaxe** [comment] 2021-11-22 19:37
In case we are talking about https://github.com/squ1b3r/Djaneiro ... that's a 3rd-party package providing a dedicated syntax for Djaneiro Python. It's a tmLanguage file, which wouldn't be surprising to fail in some scenarios.

As I see https://github.com/squ1b3r/Djaneiro/issues/127, I'll close this one as invalid.

**Closed by deathaxe** 2021-11-22 19:37 UTC
Labels: bug
