### ISSUE TITLE
[Go] Wrong symbol kinds

### ISSUE THREAD

**Issue by genexpr** [sublimehq/Packages#3055] opened 2021-09-28 20:31 UTC
### Expected behavior

For Completion Metadata for Go's symbols:
- Types should be of kind `type`
- Methods should be of kind `function`

### Actual behavior

- Types are of kind `variable`
- Methods are of kind `variable`
- Constants are of kind `variable`
- Yet package-level variables themselves have no kind at all (icon is missing)

### Steps to reproduce

Use Goto Symbol in a file with Go source code and see the symbol names and their corresponding _kind_ icons.
Be sure the file has all possible top-level declarable things in Go - type, variable, constant, function, method.

**Comment by deathaxe** [comment] 2021-09-29 17:51
While const variables use `variable`, which is correct, the others appear to have correct type info in ST4115.

![grafik](https://user-images.githubusercontent.com/16542113/135322211-974c5f86-d4d2-4c32-b1a0-1cada1d07b0c.png)

**Comment by deathaxe** [comment] 2021-10-31 09:36
Any comment on this? Otherwise I'd close it as working as expected.

**Comment by rwols** [comment] 2021-10-31 10:11
@mitranim

**Comment by genexpr** [comment] 2021-10-31 15:29
I just checked build 4121 (official release).
A few issues:

1. `package main` is marked as `n` - navigation. I am not sure this is right, maybe namespace - `a` - would be more appropriate?
2. `var foo = "foo"` does not have a corresponding symbol at all. It's just blank. While a constant `const bar = "bar"` does have the `v` mark.
3. `func (b Baz) Do() {}` is marked as `v`, but it's a method, not a variable. Perhaps it should be `f` - function?

This is the snippet of code I used for testing:
```
package main

var foo = "foo"

const bar = "bar"

func main() {}

type Baz struct{}

func (b Baz) Do() {}
```

**Comment by deathaxe** [comment] 2021-10-31 16:16
Thank's for clarification.

Kind symbols are derived from scope names automatically. No chance to configure it at the moment.

1. `n` means `namespace` as all kinds of namespaces/packages/modules are scoped `entity.name.namespace`.
2. `var foo` has no symbol as the variable is not scoped `variable.other`. That needs to be fixed.
3. is caused by a fautly selector in a symbol list definition, which itself isn't needed.

**Closed** 2021-12-18 09:04 UTC
