### ISSUE TITLE
[C++.sublime-syntax] Strange highlight

### ISSUE THREAD

**Issue by KangShanshuo** [sublimehq/Packages#3687] opened 2023-03-25 15:27 UTC
### What happened?

Here is my code.
<img width="535" alt="截屏2023-03-25 20 19 55" src="https://user-images.githubusercontent.com/107802718/227726287-308678b2-9091-45d5-8e80-2b03142fc7a5.png">
Difference between "<" and ">=" look strange.
Platform: macOS Ventura with M1 Pro
Version: Build 4143
I really hope you can solve this problem soon, this is not the first time I meet this kind of problem.
p.s. I like Sublime Text very much!!

**Comment by jfcherng** [comment] 2023-03-25 15:42
duplicate of #2216

**Closed by jfcherng** 2023-03-25 15:42 UTC
Labels: T: bug, duplicate, C: Syntax
