### ISSUE TITLE
[Java] wrong color at tag opening

### ISSUE THREAD

**Issue by wildeee** [sublimehq/Packages#527] opened 2016-07-14 15:39 UTC
Opening tag colored as red, and it's closure in white
[Dao.txt](https://github.com/sublimehq/Packages/files/364132/Dao.txt)

**Comment by wbond** [comment] 2016-07-14 16:19
I'm not that familiar with Java. Can you describe in a little more detail, and possibly post a screenshot or two?

**Comment by wildeee** [comment] 2016-07-14 16:40
Sure! The character shown in the image should be white, I guess.
![sem titulo](https://cloud.githubusercontent.com/assets/5889381/16847611/47e29672-49c8-11e6-8da0-4a8a1c325fdf.png)

**Comment by wbond** [comment] 2016-07-18 12:19
Ah, so generic type information. Thank you for the bug report!

**Comment by dpdrmj** [comment] 2016-08-13 15:56
i cannot reproduce the bug. However, copying the code from the file(Dao.txt) shows it again.

**Comment by wbond** [comment] 2016-12-15 14:56
This was fixed by c4032ac7f8e952204892b385097ca32449343418 and will be part of the next dev build

**Closed by wbond** 2016-12-15 14:56 UTC
Labels: bug

**Comment by wildeee** [comment] 2016-12-15 15:27
Thanks bro!
