### ISSUE TITLE
[Python] Breaks on certain dict

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#3649] opened 2023-02-01 14:32 UTC
### What happened?

```python
x = {
  "diagnostics": [
    {
      "message": "Type '{ _client: { _user?: { [x: string]: unknown; id: string; anon?: boolean | undefined; name?: string | undefined; role?: string | undefined; teams?: string[] | undefined; username?: string | undefined; ... 18 more ...; roles?: string[] | undefined; } | { ...; } | undefined; ... 202 more ...; commitMessage: (id: string...' is missing the following properties from type 'Channel<DefaultGenerics>': _client, type, id, data, and 74 more."
    },
  ]
}
```

<img width="677" alt="Screenshot 2023-02-01 at 15 31 48" src="https://user-images.githubusercontent.com/153197/216071224-48ebe8af-59ff-45c1-9326-5abd2202161a.png">

**Comment by jfcherng** [comment] 2023-02-01 14:41
This seems to be caused by format string + imbalanced brackets.

Minimal reproduce:

```py
{
    "y": "{:{}"
}
```

**Comment by rchl** [comment] 2023-02-01 14:45
Just a of-the-top suggestion that comes to mind: maybe don't assume that `{`/`}` are used for formatting in mapping sequences and only assume this in plain strings.

**Comment by deathaxe** [comment] 2023-02-01 17:52
Strictly implementing https://docs.python.org/3.6/library/string.html#formatstrings should fix the issue.

**Comment by rchl** [comment] 2023-02-01 19:01
Would that mean that you have to consume the whole string to see if there is `.format` after it and then rewind and start parsing again?

**Comment by michaelblyons** [comment] 2023-02-01 19:25
> Would that mean that you have to consume the whole string to see if there is `.format` after it and then rewind and start parsing again?

Don't do that. People can re-use a format string:

```py
fmt = '{0:>5} | {1:12} | {2}'
print(fmt.format(foo))
print(fmt.format(bar))
```

**Comment by FichteFoll** [comment] 2023-02-01 21:09
The format spec *may* be anything that the object's `__format__` method accepts, though the special example given above seems rather unlikely to occur in practice. If it makes things to complicated, we can definitely axe it and only support actual format specs along with arbitrary nesting inside of the spec. It's been a long while, but I assume that without branching the current state was just easier to implement.

**Comment by michaelblyons** [comment] 2023-02-01 21:22
Can we count on the punctuation that opens the string to close it (i.e. format strings can't contain that `"` or `'`)? And if so, can we `embed` the string contents rather than `push`ing them so that it _will_ terminate with the `punctuation.def.str.end`?

**Comment by deathaxe** [comment] 2023-02-02 19:31
The tricky thing is that some pieces of format specs seem to support full expressions.

```
index_string      ::=  <any source character except "]"> +
```

**Comment by michaelblyons** [comment] 2023-02-02 20:49
> support full expressions.

But it's not actually true, is it? If you start the string with `'`, then another `'` _will close it_ unless I haven't tried hard enough.

```py
>>> f'{None:{'bar'}}'
  File "<stdin>", line 1
    f'{None:{'bar'}}'
              ^^^
SyntaxError: f-string: expecting '}'

>>> f'{None:['bar']}'
  File "<stdin>", line 1
    f'{None:['bar']}'
              ^^^
SyntaxError: f-string: expecting '}'

>>> f'{None:["b'ar"]}'
  File "<stdin>", line 1
    f'{None:["b'ar"]}'
                ^^
SyntaxError: f-string: expecting '}'

>>> f'{None:{"b'ar"}}'
  File "<stdin>", line 1
    f'{None:{"b'ar"}}'
                ^^
SyntaxError: f-string: unterminated string
```

My problem with the OP is not that Python.sublime-syntax thinks it's a format string. I'm more concerned that it breaks out of the string termination.

**Closed** 2023-07-15 15:52 UTC
Labels: T: bug, C: Syntax
