### ISSUE TITLE
[Markdown] Fenced code block followed by thematic break incorrectly highlighted as setext heading

### ISSUE THREAD

**Issue by jwortmann** [sublimehq/Packages#2947] opened 2021-08-11 03:41 UTC
``````markdown
```
This is a fenced code block, followed by a thematic break
```
---
``````

![markdown1](https://user-images.githubusercontent.com/6579999/128966010-0046f0cc-4266-434e-8049-4e605c258b40.png)

According to the CommonMark spec for [Setext headings](https://spec.commonmark.org/0.30/#setext-headings), the lines of text in a setext heading

> must be such that [...] they cannot be interpretable as a code fence [...]

The HTML preview on [https://spec.commonmark.org/dingus](https://spec.commonmark.org/dingus/?text=%60%60%60%0AThis%20is%20a%20fenced%20code%20block%2C%20followed%20by%20a%20thematic%20break%0A%60%60%60%0A---%0A) indeed displays it as a normal code block and horizontal rule (thematic break).

---

- Sublime Version: 4113
- OS Version: Windows 10

**Comment by deathaxe** [comment] 2021-08-11 08:51
That's caused by fenced code-blocks being matched as part of a `paragraph` (see https://spec.commonmark.org/0.30/#paragraphs) which is obviously wrong.

The fix is quite simple but either would need to be messed into https://github.com/sublimehq/Packages/pull/2925 or needs that PR merged first. The `fenced-codeblock` context it introduces simply needs to be included in `main` instead of `paragraph` then.

Already found several other such issues in current Markdown implementation. I guess this ends up in another rewrite when also taking new branching opportunities with regards to bold/italics into account.

**Closed** 2021-09-09 18:55 UTC
Labels: bug
