### ISSUE TITLE
[Bash] coloring falls off after bash-if-condition in lesspipe.sh

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#2917] opened 2021-07-27 22:24 UTC
- Sublime Version: v4
- OS Version: Focal

https://github.com/wofr06/lesspipe/blob/38c8be645f791cf266bbeb6b0a0b2596ddc9d29e/lesspipe.sh#L564-L575

![image](https://user-images.githubusercontent.com/133706/127235098-7f133190-9535-4f93-bd0e-691ee6326250.png)

**Comment by rwols** [comment] 2021-07-27 22:32
Duplicate of https://github.com/sublimehq/Packages/issues/2881, should be fixed by https://github.com/sublimehq/Packages/pull/2882

**Closed** 2021-07-27 22:33 UTC
