### ISSUE TITLE
[C++] Macro without semicolon breaks subsequent syntax

### ISSUE THREAD

**Issue by ratijas** [sublimehq/Packages#3452] opened 2022-07-25 10:15 UTC
### What happened?

Broken:
![broken](https://user-images.githubusercontent.com/6737986/180753347-10708051-3481-42db-940e-275ce974706a.png)

Kinda fixed:
![fixed](https://user-images.githubusercontent.com/6737986/180753353-e622674f-91f2-4d77-a630-27d7ca1865b1.png)

Also kinda fixed:
![also fixed](https://user-images.githubusercontent.com/6737986/180753568-204db31e-8f42-4358-983a-129449e655f1.png)

Minimal reproducible example:

 ```cpp

MACRO(f())

class MyClass
{
public:
    MyClass()
    {}
}
```

(even GitHub highlighter stumbles upon it)

**Comment by deathaxe** [comment] 2022-07-30 08:25
Duplicate of #1034

**Closed by deathaxe** 2022-07-30 08:25 UTC
Labels: bug
