### ISSUE TITLE
Grouped conditions highlight error

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#2307] opened 2020-03-09 11:25 UTC
- Sublime Version: Sublime Text Build 3211
- OS Version: Ubuntu 16.04.6 LTS

```bash
	while ! { [[ cond1 ]] && \
	      [[ cond2 ]] ; } ; do
		# .....
	done
```

**Comment by rwols** [comment] 2020-03-09 11:42
Likely fixed by https://github.com/sublimehq/Packages/pull/1863

**Comment by jfcherng** [comment] 2020-03-09 11:46
![image](https://user-images.githubusercontent.com/6594915/76210192-95445800-623e-11ea-9011-8982a0114073.png)

Don't think so. `[[` and `]]` is not correctly done.

**Comment by rwols** [comment] 2020-03-09 11:48
Interesting. I'm at work so I don't have a lean-and-mean ST. It seems to be caused by the exclamation mark character.

**Comment by jfcherng** [comment] 2020-03-09 11:49
![image](https://user-images.githubusercontent.com/6594915/76210428-169bea80-623f-11ea-9ea5-d694f421111a.png)

shellcheck don't think its valid Bash btw.

**Comment by rwols** [comment] 2020-03-09 12:00
Well it works in bash 4.4, so it must be correct :)

```bash
while   { true; }; do echo foo; done
while ! { true; }; do echo bar; done
```

**Comment by stdedos** [comment] 2020-03-09 12:13
@jfcherng I should've gone for the `: # comment` instead of `# comment`. However, I was afraid that someone might try to run it at the terminal (and idk if that's an infinite loop).

In my code, `do...done` trims a string until empty (which is used to check `while...do` stuff); and at that point it returns 1 (so it's not infinite).

**Comment by jfcherng** [comment] 2020-03-09 12:18
> @jfcherng I should've gone for the `: # comment` instead of `# comment`. However, I was afraid that someone might try to run it at the terminal (and idk if that's an infinite loop).

Ah, yeah! That's valid code.

![image](https://user-images.githubusercontent.com/6594915/76212336-333a2180-6243-11ea-806e-511de660dd50.png)

**Comment by deathaxe** [comment] 2020-03-11 19:27
According to https://www.gnu.org/software/bash/manual/bash.pdf chapter "3.2.4.3  Grouping Commands" the curlies are valid grouping punctuations such as parentheses here. Therefore needs to be destinguished from the expansion braces in such situations. 

Same for the `!` which is not matched as operator.

**Closed** 2020-07-15 20:31 UTC
