### ISSUE TITLE
[Dlang] shortened function syntax highlighted as error

### ISSUE THREAD

**Issue by crazymonkyyy** [sublimehq/Packages#4012] opened 2024-07-22 01:39 UTC
### What happened?

![Screenshot_2024-07-21-19-32-16_16311](https://github.com/user-attachments/assets/82d0cd8c-527a-434f-bbca-85ef8daef14e)

**Comment by deathaxe** [comment] 2024-07-22 10:52
Duplicate of #3894

**Comment by deathaxe** [comment] 2024-07-22 10:53
Fixed in ST4175+

**Closed by deathaxe** 2024-07-22 10:52 UTC
Labels: duplicate
