### ISSUE TITLE
[CSS] Ctrl+Space doesn't expand values properly

### ISSUE THREAD

**Issue by burgerkalif** [sublimehq/Packages#1452] opened 2018-03-07 22:15 UTC
Immediately after you have tab completed a property, pressing Ctrl+Space should show completions for possible values. But it doesn't, it goes back and shows completions for properties still, UNLESS you insert an arbitrary character before pressing Ctrl+Space.

**Comment by burgerkalif** [comment] 2018-03-08 10:43
Yes, but that's not what I meant. Expanding properties (like display) works fine. It's when you hit ctrl+space immediately after you expanded a property (when you want suggestions for possible VALUES, like block, inline etc.). Then ST3 goes back and suggest properties for you, which is not what you want.

**Comment by burgerkalif** [comment] 2018-03-08 10:47
I'm not the only one experiencing this:
https://forum.sublimetext.com/t/css-autocomplete-suggests-properties-instead-of-values/24334

**Comment by FichteFoll** [comment] 2018-03-08 10:50
Yes, I meant I also pressed ctrl+space immediately after completing `display`.

It works just fine for me: https://x0.at/HW8.mp4

**Comment by burgerkalif** [comment] 2018-03-08 11:22
Ok thanks. Strange. I disabled Emmet myself, but to no avail. Still the same issue. Weird

**Comment by deathaxe** [comment] 2021-08-19 18:51
Can't reproduce, too. Several changes have been made to ST's core auto-completion system as well as CSS's completion plugin. Hence I close this one.

**Closed by deathaxe** 2021-08-19 18:51 UTC
