### ISSUE TITLE
[Markdown] "unterminated" `~` (tilda) gives error in parsing

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#3170] opened 2021-12-16 17:12 UTC
### What happened?

IIRC, technically speaking, `~` "always starts" an inline strikethrough.

However, in GFM, that does not appear to be the case:

> ```
> * bat (~/bat)
> ```
> * bat (~/bat)

I know that the syntax highlighting is Markdown (and not Commonmark/GFM), and instead, I'd like to clarify:

* Are you going to make a Commonmark syntax highlight?
* ... GFM?

In case that you don't want to mess with the Markdown syntax highlight itself, because legacy reasons. Or:

* Do you consider this a bug to be dealt with?

**Comment by deathaxe** [comment] 2021-12-16 17:29
See https://github.com/SublimeText-Markdown/MarkdownEditing/issues/637 for explanation. #3147 is caused by the same reason.

**Comment by stdedos** [comment] 2021-12-16 20:24
And I wanted to open it against https://github.com/SublimeText-Markdown/MarkdownEditing/! 😛

"That's okay", I guess. Thank you for the quick points!

**Comment by Alexey-T** [comment] 2021-12-16 20:27
Is it a problem to make this in syntax file?: ending including `|$`, ie it's closing at the end of line.

**Comment by deathaxe** [comment] 2021-12-16 21:44
This issue can be fixed with ST4's "branching" feature.

The current release of MarkdownEditing and the resulting PR #3167 to sync its syntax back to this repo is a milestone which represents the last ST3 compatible version of the syntax definition.

From this point on, I'll go ahead to introduce some branching in order to properly address all those emphasis stuff. Bold/Italics also suffer from the issue described here.

**Comment by deathaxe** [comment] 2021-12-23 12:51
Appears Github's GFM parser doesn't follow its own specs (see: https://github.github.com/gfm/#strikethrough-extension-).

It requires strikethough to be wrapped into 2 `~`, but the following line is fully striked

```
This ~text~~~~ is ~~~~curious~.
```

This ~text~~~~ is ~~~~curious~.

**Comment by stdedos** [comment] 2021-12-23 17:52
Maybe it's just "legacy" Markdown features preserved. 😕 

I'd be happy to report it to ~~https://github.com/isaacs/github/issues~~ https://github.com/github/feedback/discussions/new, but I am not sure anyone may bother with it (e.g. https://github.com/isaacs/github/issues/1970 is still active)

**Closed** 2022-05-07 09:48 UTC
Labels: enhancement
