### ISSUE TITLE
C code: ST4 fails to (not) highlight (in)active code in #elif 1 / #elif 0 branch

### ISSUE THREAD

**Issue by annazolkieve** [sublimehq/Packages#2873] opened 2021-06-17 10:24 UTC
C code: ST4 fails to (not) highlight (in)active code in `#elif 1` / `#elif 0` branch. Even in safe mode. Please fix.
![image](https://user-images.githubusercontent.com/46918093/120542890-50cd4b00-c3f4-11eb-92dd-09702bf84b84.png)
![image](https://user-images.githubusercontent.com/46918093/120542918-5b87e000-c3f4-11eb-9f3c-6cecf0c571ef.png)

**Comment by deathaxe** [comment] 2021-08-19 10:39
Duplicate of #2385

**Closed by deathaxe** 2021-08-19 10:39 UTC
Labels: bug
