### ISSUE TITLE
[JavaScript] Highlighting of string template literals is broken

### ISSUE THREAD

**Issue by hkdobrev** [sublimehq/Packages#213] opened 2016-02-26 09:34 UTC
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Sometimes the highlighting of JS literals is broken when you have quotes inside of backticks.

Open this file in Sublime: https://github.com/sindresorhus/refined-github/blob/4d90cfcacc90c521148376f338de206af74880ed/extension/content.js#L162 and you'd see the literal on line 162 is not properly highlighted and it seems like dozens of lines below it are part of the string.

**Comment by wbond** [comment] 2016-02-26 10:13
What build of Sublime Text are you using?

**Comment by hkdobrev** [comment] 2016-02-26 10:29
Build 3107

I've experienced the issue with the last few dev builds, but I think it wasn't there a few builds ago.

**Comment by wbond** [comment] 2016-02-26 10:37
Hmm, so the issue isn't specifically with the template literal, but rather with the surrounding `{}` block.

https://github.com/sindresorhus/refined-github/blob/4d90cfcacc90c521148376f338de206af74880ed/extension/content.js#L159-L170.

It is unfortunate that a block can be an object literal or just anonymous, since that makes it extremely difficult to parse properly without backtracking. Currently the parser is expecting a block such as that that is not following a control structure to be an object literal.

**Comment by dcolthorp** [comment] 2016-02-27 01:52
Also in 3107, this line leaves the rest of the buffer highlighted as a string:

<pre> `activeFilters.{${this.get('filterProperties').map(p => p.concat('.[]')).join(',')}}`, {</pre>

e.g.
<img width="1080" alt="screen shot 2016-02-26 at 8 51 38 pm" src="https://cloud.githubusercontent.com/assets/8980/13369984/cccc0e9c-dcca-11e5-9d41-11be38b1cf15.png">

**Comment by wbond** [comment] 2016-02-29 12:01
@dcolthorp The example you posted seems to work properly with the latest version of JavaScript.sublime-syntax that is contained in this repo.

**Comment by wbond** [comment] 2016-03-01 20:29
Jon pointed out the anonymous `{}` construct at the statement level can never be an object. Thus, I've been working on enhancing the syntax to track the state to determine if an object literal or `{}` block is the appropriate parsing at a given point.

**Comment by wbond** [comment] 2016-03-01 21:17
@hkdobrev This should be resolved by 62d142a416d44d18785bf03b5a1ded1badcd8577

**Closed by wbond** 2016-03-01 21:17 UTC

**Comment by hkdobrev** [comment] 2016-03-01 22:12
Thank you @wbond!
