### ISSUE TITLE
[Lua] table assignment followed by label declaration confuses do-end block

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#2821] opened 2021-05-16 08:33 UTC
- Sublime Version: 4105
- OS Version: macOS

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2431823/118390923-ee253280-b631-11eb-82c5-fd245a147550.png">

```lua
for k, v in ipairs(arg) do
    _G[k] = v
    ::LABEL::
end
```

**Comment by deathaxe** [comment] 2021-06-02 19:24
This issue is caused by missing semicolon after `v` in line 2 which causes first `::` in line 3 being scoped as accessor. I guess that's the reason why `LABEL` is underlined?

**Comment by rwols** [comment] 2021-06-06 00:25
I don't think a missing semicolon is invalid, though I'm not a Lua expert.

```lua
local function loadArgs()
    for _, v in ipairs(arg) do
        local key, value = v:match '^%-%-([%w_]+)%=(.+)'
        if not key then
            goto CONTINUE
        end
        if value == 'true' then
            value = true
        elseif value == 'false' then
            value = false
        elseif tonumber(value) then
            value = tonumber(value)
        elseif value:sub(1, 1) == '"' and value:sub(-1, -1) == '"' then
            value = value:sub(2, -2)
        end
        _G[key:upper()] = value
        ::CONTINUE::
    end
end
```

found here: https://github.com/sumneko/lua-language-server/blob/4647fad6816cc78d7fb9970077d33763afd710df/main.lua#L19-L37

**Comment by deathaxe** [comment] 2021-06-06 07:56
Nevertheless, syntax definition expects semicolons.

**Comment by deathaxe** [comment] 2021-06-06 08:33
Appears semicolons are optional and needed only if several statements are to be written in one line - same as python.

see: https://stackoverflow.com/questions/16862337/lua-semicolon-conventions

**Comment by rosik** [comment] 2021-06-18 15:40
Here's a better link, it's the reference manual: https://www.lua.org/manual/5.1/manual.html#2.4.1

**Comment by baidwwy** [comment] 2021-07-25 16:32
@Thom1729

**Comment by Thom1729** [comment] 2021-08-04 17:41
Should be fixed by the linked PR.

**Closed** 2021-08-17 19:36 UTC
