### ISSUE TITLE
[HTML] ease syntax parsing of custom/foreign tags

### ISSUE THREAD

**Issue by dakira** [sublimehq/Packages#2713] opened 2021-02-08 15:13 UTC
- Sublime Version: 3.2.2 (3211)
- OS Version: Big Sur

``` html
<livewire:element>
```

<img width="307" alt="bad-error-highlighting.png" src="https://user-images.githubusercontent.com/576555/107517482-196d3100-6bae-11eb-9114-4fc2ad3ef970.png">

In this case the colons shouldn't be marked as errors. The same used to be true for dots but was fixed for ST4 in #2407.

Related discussion: https://forum.sublimetext.com/t/how-to-remove-dot-marks-dont-know-how-to-name-it/52550
Related PR: #1784 by @deathaxe, but it doesn't actually fix the problem.

Update: For the dot this is fixed in ST4 (see below), it's still a problem with the colon (:), though.
Update2: changed title as per [this comment](https://github.com/sublimehq/Packages/issues/2713#issuecomment-780078417)

**Comment by jfcherng** [comment] 2021-02-08 15:14
This has been fixed in a certain commit of the ST 4 branch.

**Comment by dakira** [comment] 2021-02-08 15:16
@jfcherng can it be backported? As far as I know ST4 isn't ready for use, yet, right?

**Comment by jfcherng** [comment] 2021-02-08 15:34
> can it be backported? 

Yes. https://github.com/sublimehq/Packages/pull/2407/files

> As far as I know ST4 isn't ready for use, yet, right?

Probably. But it's available.

**Comment by dakira** [comment] 2021-02-08 16:11
@jfcherng Thanks.. this works. The problem with the colon persists, though.

**Comment by jfcherng** [comment] 2021-02-08 16:21
> @jfcherng Thanks.. this works. The problem with the colon persists, though.

True. But that should be an easy fix.

**Comment by dakira** [comment] 2021-02-10 13:44
@jfcherng thanks for the help.. updated the issue.

**Comment by wbond** [comment] 2021-02-10 14:08
A colon sounds like an XML document with a namespace, not HTML. My hunch is you should be using the XML syntax.

**Comment by deathaxe** [comment] 2021-02-16 19:51
Namespaced tags are not supported by HTML. See the `notes box` at https://html.spec.whatwg.org/multipage/syntax.html#elements-2

Actually Firefox or Chrome accept those colons or seem to fail silently by ignoring the namespace part. Not sure how foreign tags such as SVG or MathML are handled in detail though. They may support namespaces as they are XML.

The root cause for displaying colons as illegals is the attempt to strictly enforce `custom elements` highlighting. Those don't support/accept colons. (see: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts)

https://github.com/sublimehq/Packages/blob/5554fd25bcd43f642fa998a9f722f2cd43a6a254/HTML/HTML.sublime-syntax#L157-L162

A link in issue https://github.com/sublimehq/Packages/issues/1822 brings us to: https://html.spec.whatwg.org/multipage/syntax.html#start-tags

The page doesn't mension `custom elements` but `foreign elements` only. I thought they are synonyms, but than I found ...

> In the HTML syntax, tag names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that, when converted to all-lowercase, matches the element's tag name; tag names are case-insensitive.

It's not about a colon, but according to that sentence we probably should not scope upper-case letters illegal in non-html tags.

According to https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state all characters accept ascii whitespace and some punctuation are valid in tag names. That's the rule _HTML (Plain).sublime-syntax_ applies in general.

All of that gets me wondering whether we should ease syntax parsing of custom/foreign tags by dropping the pattern of the above lines and just leave the second one of that context.

The only thing we'd loose is questionable illegal highlighting of uppercase letters in non-html tags. I'd find that acceptable.

**Closed** 2021-03-10 16:26 UTC
