### ISSUE TITLE
[Makefile][sublime-syntax] back slash is a line continuation

### ISSUE THREAD

**Issue by shaik7abdul7khallik** [sublimehq/Packages#2056] opened 2019-08-20 11:21 UTC
`# something \`
`temp := hello`

Back slash is a line continuation in Make files.
The second line `temp := hello` also becomes a comment that should look greyed out due to `\` in first line. But its not greyed out.

**Comment by jfcherng** [comment] 2019-08-20 11:32
![image](https://user-images.githubusercontent.com/6594915/63343704-35a95c80-c381-11e9-9614-641492dba186.png)

cannot reproduce

**Comment by deathaxe** [comment] 2019-08-20 18:08
Duplicate of issue #1938 fixed by PR #1944 which is not part of ST3207/3208.

**Closed** 2019-08-21 04:49 UTC
