### ISSUE TITLE
Color of functions

### ISSUE THREAD

**Issue by bork1991** [sublimehq/Packages#616] opened 2016-09-10 11:33 UTC
See that image please:
https://i.gyazo.com/ba49e076157d403615ae2713ae92bbb4.png

**Comment by MattDMo** [comment] 2016-09-10 15:07
I see it. What is your question? Please close this issue if #617 is your actual problem.

**Comment by bork1991** [comment] 2016-09-11 06:19
are you slowly reaching? are you see these BUG now here :rofl:?

**Comment by jfcherng** [comment] 2016-09-11 06:38
Maybe a duplicate of https://github.com/sublimehq/Packages/issues/612

**Comment by bork1991** [comment] 2016-09-11 06:58
nope. that about array_map(closure(array_map(closure(func))))), 612 is about lighting php code blocks in quotes and in HEREDOC syntax.

**Comment by jfcherng** [comment] 2016-09-11 07:51
Uh, are we on the same issue 612?
![image](https://cloud.githubusercontent.com/assets/6594915/18415963/867072ae-7837-11e6-9296-d2ed3831ef54.png)

**Comment by bork1991** [comment] 2016-09-11 08:07
ahh sorry i'm declined didn't see before posting. ok, closed.

**Comment by wbond** [comment] 2016-09-21 15:19
@bork1991 Can you indicate what build of Sublime Text you are using?

**Comment by wbond** [comment] 2016-12-15 16:05
If you are seeing a bug with build 3126, please create a new issue, and be sure to include example syntax that causes the issue.

**Closed by wbond** 2016-12-15 16:05 UTC
Labels: bug
