### ISSUE TITLE
[C/C++] Sublime Merge fails to load sublime-syntax

### ISSUE THREAD

**Issue by Adarma** [sublimehq/Packages#4030] opened 2024-08-18 16:14 UTC
### What happened?

I have a slightly modified version of `C++.sublime-syntax` at `"C:\Users\USER\AppData\Roaming\Sublime Text\Packages\C++\C++.sublime-syntax". It just adds some custom types and macros.

It was working fine in both Sublime Text and Sublime Merge until these lines were added:

https://github.com/sublimehq/Packages/commit/e4e5273d8ca764ebcd79b2ecfbed592036944265#diff-eaf5cc6c22ae062900a7cec575caea115919f5086157815d857dc82d8237e6d4R330-R341

Now Sublime Merge fails to load the package with:
![image](https://github.com/user-attachments/assets/16969afa-1c51-424f-9a98-50a449b0a9ee)

I suppose it is because I have an override file and the c# file is now not found relative to it or something...

If I comment those lines out, Sublime Merge loads fine

**Comment by deathaxe** [comment] 2024-08-18 17:41
Duplicate of #4028.

**Closed by deathaxe** 2024-08-18 17:41 UTC
