### ISSUE TITLE
[C++] Syntax highlighting for Raw String Literals broken

### ISSUE THREAD

**Issue by nik3daz** [sublimehq/Packages#1349] opened 2017-12-07 04:32 UTC
Syntax highlighting seems to break if the raw string begins on a new line of its own, without a non-whitespace character in front of it.

![image](https://user-images.githubusercontent.com/1677402/33698825-2e617226-db63-11e7-85c9-e84fd612a240.png)

**Comment by rwols** [comment] 2017-12-08 19:22
Duplicate of https://github.com/sublimehq/Packages/issues/1206

**Closed** 2018-11-28 03:31 UTC
