### ISSUE TITLE
Invalid JS highlighting for default Twilight theme

### ISSUE THREAD

**Issue by minitauros** [sublimehq/Packages#147] opened 2016-02-10 09:39 UTC
_I created a post on the forums before I saw I'm probably supposed to open an issue here, so for a screenshot / the original post, see https://forum.sublimetext.com/t/sublime-3103-js-highlighting-incorrect-for-default-twilight-theme/17380._

**Issue**
Since I downloaded 3103, the highlighting of Javascript code has slightly changed. I can't say it is incorrect - as who knows, it might be intended - but it feels slightly less accurate.

(see screenshot mentioned above) 

...as you can see, most of the syntax is now highlighted in blue, where there used to be more yellow-ish (for this and for $, and I also think vars like complete_questionnaire_container in the screenshot weren't blue before).

**Comment by wbond** [comment] 2016-02-10 11:15
This is a duplicate of #141. There is some conversation there that explains what changed and why.

**Closed by wbond** 2016-02-10 11:15 UTC
