### ISSUE TITLE
Arrow Function Object/Array Unpacking (Javascript)

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [sublimehq/Packages#1430] opened 2018-02-16 12:32 UTC
I am not sure if this is an error or not so could you please take a look at what I have found?

When I try Object and Array argument unpacking for the arrow function with the arguments on separate lines the highlighting of the arguments seems off.

Also, if I pass the same arrow function with the arguments on separate lines into another function the function's inner code highlighting also seems to be off.

I have not included Array unpacking in this but Array unpacking seems to have the same result as object unpacking.
![screen shot 2018-02-16 at 7 27 13 am](https://user-images.githubusercontent.com/10747532/36307592-dcd59292-12ea-11e8-993e-c2d55bc75c86.png)

Actual code
```text
/* good argument highlighting
  when arguments on on one line
*/
({one, two}) => {
  // good inner function highlighting
  if (one) return
  if (two) return
}

/* bad argument highlighting
  when arguments on separate lines
*/
({
  one,
  two,
}) => {
  // good inner function highlighting
  if (one) return
  if (two) return
}

/* good argument highlighting
  when arguments on one line
  and passed into a function
*/
console.log(({one, two}) => {
  // good inner function highlighting
  if (one) return
  if (two) return
}

/* bad argument highlighting
  when arguments on separate lines
  and passed into a function
*/
console.log(({
  one,
  two,
}) => {
  // bad inner function highlighting
  if (one) return
  if (two) return
})

/* good argument highlighting
  when using "function" instead of "=>"
  when arguments on separate lines
  and passed into a function
*/
console.log(function({
  one,
  two,
}) {
  // good inner function highlighting
  if (one) return
  if (two) return
})
```

**Comment by Thom1729** [comment] 2018-02-16 14:37
For technical reasons, it's not actually possible to reliably tell an arrow function argument list from a parenthesized expression. The JavaScript syntax definition uses an imperfect method to guess. It will never guess that there is a line break between the beginning of the arguments list and the `=>` itself. In order to detect arrow functions correctly, Sublime would need a significantly more powerful parser.

However, the syntax definition is designed so that when it guesses wrong and parses an arrow function parameter list as a parenthesized expression, upon seeing the `=>` it will recover and correctly parse the following expression or block as the body of an arrow function. You can see that even though examples 2 and 4 do not mark the parameter list correctly, the `=>` token is correctly marked.

All that said, example 4 is a bug. It is parsing the block constituting the arrow function body as though it were an object literal. It shouldn't be doing that. Here's a minimal example:

```js
(
  ()
  => { return; }
);
```

**Comment by FichteFoll** [comment] 2018-02-16 14:39
This is a limitation of the syntax engine which only allows parsing one line at a time. The problem with arrow functions is that until the arrow is found, it doesn't have to be a function because it is valid syntax otherwise. That's why st cannot match parameters over a multi-line arrow function.

**Comment by BebeSparkelSparkel** [comment] 2018-02-16 17:29
The arguments aren't a big deal, but example 4 that @Thom1729 pointed out is with motivated me enough to post this issue.

**Comment by user-982634** [comment] 2018-05-24 18:27
@BebeSparkelSparkel 

Since the issue is fixed, can you please close it. Thanks.

**Closed** 2018-05-25 11:33 UTC
