### ISSUE TITLE
HIghtlight problem when prefix derefference for Perl

### ISSUE THREAD

**Issue by KES777** [sublimehq/Packages#2017] opened 2019-07-27 10:42 UTC
For the code from #1495 
```
sub x {
  my( $c ) =  shift;
  my $ctrl =  $c->stash->{ control } //=  {};
  my $id = scalar keys %{ $ctrl->{ hello } };
}
```

One problem is left for `%{ ... }` syntax:
![_3](https://user-images.githubusercontent.com/799021/61993375-bd969200-b073-11e9-8f41-872bc6fceae1.jpg)

`Modern Perl` syntax highlight OK:
![_2](https://user-images.githubusercontent.com/799021/61993391-f5053e80-b073-11e9-9a0f-a081634aafa2.jpg)

PS. this is Color scheme -> legacy -> Espresso libre

**Comment by deathaxe** [comment] 2019-07-28 13:57
The strange looking colors you see are caused by an unlucky choise of scopes. The whole `%{...}` is scoped as `variable.other`, which causes everything not assigned to any other scope to be highlighted the same. _I already replaced that by `meta.variable` in an internal dev branch to fix that issue._

Are `stash`, `control` and `hello` really functions as ModernPerl scopes them as such? The real meaning of `stash` depends on the object type, I think, while `control` and `hello` are dictionary keys?

**Comment by KES777** [comment] 2019-07-29 06:44
`stash` is function. Word after `->` always the function.  `control` and `hello` are interpreted as strings inside `{ ... }`
If I rewrite  `->{ +control }` now `control will be interpreted as function (code is interpreted as expression)

**Comment by deathaxe** [comment] 2019-08-14 17:44
@KES777: You may checkout #2048. It should fix this issue next to many more.

**Closed** 2019-10-17 19:12 UTC
