### ISSUE TITLE
[Python] meta.function.parameters.python keyword.operator.unpacking.mapping.python 

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1398] opened 2018-01-28 23:49 UTC
![image](https://user-images.githubusercontent.com/5332158/35488776-ecd23bc0-0474-11e8-8915-8d6ec8e962ca.png)

It should have the scope `meta.function.parameters.python keyword.operator.unpacking.mapping.python` like this one:

![image](https://user-images.githubusercontent.com/5332158/35488785-103943d8-0475-11e8-8819-d557ae58388b.png)

But only have the scope `meta.function.parameters.python`

```python
    def test_function_name(self,
            **kwargs):
        pass
```

Sublime Text build 3156

**Comment by FichteFoll** [comment] 2018-01-29 00:08
Duplicate of https://github.com/sublimehq/Packages/issues/1367 and should be fixed by https://github.com/sublimehq/Packages/pull/1380.

**Comment by FichteFoll** [comment] 2018-06-20 14:03
This issue can be closed.

**Closed** 2018-06-20 14:05 UTC
