### ISSUE TITLE
[JavaScript] syntax high lighting issue 2: when the name of a property of an object happens to be a preserved word

### ISSUE THREAD

**Issue by wulechuan** [sublimehq/Packages#197] opened 2016-02-22 06:20 UTC
Build 3103
==========
For example:
`abc.function = 'carry';`
This clause will cause some `)` chars that come after the clause as mismatched, the background colors of them would be magenta if the editor theme settings is Monokai.

![image](https://cloud.githubusercontent.com/assets/4899190/13211042/0cd432d4-d970-11e5-88b7-9ba4276273f1.png)

**Comment by wbond** [comment] 2016-02-22 11:29
I am not able to reproduce the issue, so I believe this was resolved with 409ccb469bca8bcc2a5c70c562d1db3428d3015f.

**Closed by wbond** 2016-02-22 11:29 UTC
