### ISSUE TITLE
[JavaScript] Syntax highlighting issue with object methods

### ISSUE THREAD

**Issue by amalk** [sublimehq/Packages#403] opened 2016-05-16 15:22 UTC
Stable Build 3114

Same method body loses highlighting when nested too deep.

![1](https://cloud.githubusercontent.com/assets/4241103/15293885/f2eacfca-1b57-11e6-8e23-cdf641f83bb0.png)
![2](https://cloud.githubusercontent.com/assets/4241103/15293886/f2ec9242-1b57-11e6-8dcd-c3cbc7f8b027.png)

**Comment by FichteFoll** [comment] 2016-05-16 18:38
Please also provide the code snippets for easier reproduction (though copy'n'paste).

**Comment by amalk** [comment] 2016-05-17 02:26
Right. The last level in this code loses the highlighting:

```javascript
    function foo() {
        TweenLite.to(el, 1, {
            onComplete: function() {
                TweenLite.to(el, 1, {
                    onComplete: function() {
                        TweenLite.to(el, 1, {
                            onComplete: function() {
                                TweenLite.to(el, 1, {
                                    onComplete: function() {
                                        TweenLite.to(el, 1, {
                                            onComplete: function() {

                                            }
                                        });
                                    }
                                });
                            }
                        });
                    }
                });
            }
        });
    }
```

**Comment by FichteFoll** [comment] 2016-05-17 11:01
I only start losing highlighting with this:

```js
function foo() {
    TweenLite.to(el, 1, {
        onComplete: function() {
            TweenLite.to(el, 1, {
                onComplete: function() {
                    TweenLite.to(el, 1, {
                        onComplete: function() {
                            TweenLite.to(el, 1, {
                                onComplete: function() {
                                    TweenLite.to(el, 1, {
                                        onComplete: function() {
                                            TweenLite.to(el, 1, {
                                                onComplete: function() {
                                                    TweenLite.to(el, 1, {
                                                        onComplete: function() {
                                                            TweenLite.to(el, 1, {
                                                                onComplete: function() {
                                                                    TweenLite.to(el, 1, {
                                                                        onComplete: function() {
                                                                            TweenLite.to(el, 1, {
                                                                                onComplete: function() {
                                                                                    TweenLite.to(el, 1, {
                                                                                        onComplete: function() {
                                                                                            TweenLite.to(el, 1, {
                                                                                                onComplete: function() {
                                                                                                 TweenLite.to(el, 1, {
                                                                                                     onComplete: function() {
                                                                                                      TweenLite.to(el, 1, {
                                                                                                          onComplete: function() {
                                                                                                           TweenLite.to(el, 1, {
                                                                                                               onComplete: function() {
                                                                                                               
                                                                                                               }
                                                                                                           });     
                                                                                                          }
                                                                                                      });     
                                                                                                     }
                                                                                                 });     
                                                                                                }
                                                                                            });  
                                                                                        }
                                                                                    });  
                                                                                }
                                                                            });  
                                                                        }
                                                                    });  
                                                                }
                                                            });
                                                        }
                                                    });
                                                }
                                            });
                                        }
                                    });
                                }
                            });
                        }
                    });
                }
            });
        }
    });
}
```
which is a side effect of the scope name becoming to long. In the empty line, the exact scope name would be:
```
source.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js meta.function-call.method.js meta.group.js meta.object-literal.js meta.block.js
```

which is *really* long and code probably shouldn't be nested that deeply, which is why ST probably assumes that any scope beyond a specific length is the result of an errorneous syntax definition and stops highlighting in order not to freeze up entirely.

**Comment by keith-hall** [comment] 2016-05-17 11:16
Interestingly, I lose highlighting and then seem to re-gain it.

![js highlighting nesting](https://cloud.githubusercontent.com/assets/11882719/15320450/4b3b7a9e-1c39-11e6-9b28-d2a05ebb172c.png)

Notice how the `1` on the inner most `TweenLite.to(` line is not highlighted, but the `onComplete: function() {` on the line afterwards is, despite being nested one level deeper by the `{`.

The `1` has the correct ending scope of `constant.numeric.js`

**Comment by FichteFoll** [comment] 2016-05-17 11:26
Confirmed:

![2016-05-17_13 26 23](https://cloud.githubusercontent.com/assets/931051/15320835/03e5d686-1c33-11e6-98e1-5267e30889c0.png)

**Comment by amalk** [comment] 2016-05-18 07:07
> which is a side effect of the scope name becoming to long

Perhaps I lose it with only a few levels of nesting because I'm running 32-bit OS?

**Comment by wbond** [comment] 2016-05-19 17:24
@FichteFoll I don't see where it is beginning with `object-literal`. It seems properly nested inside of `meta.block`, `meta.function-call` and `meta.group`.

**Comment by FichteFoll** [comment] 2016-05-19 18:23
@wbond, yes you're right, the `meta.object-literal` scope is correct. So I guess the only problem here is that the number `1` in line 10 does not receive the correct highlighting despite having the correct scope name*

**Comment by wbond** [comment] 2016-05-19 18:34
Using the scope inspector, all of the scopes seem correct. The strange thing is that the `1` is colored properly with some color schemes.

I'm looking into the core code base to see what is the cause of the weirdness.

This should probably be moved over to the core issue tracker.

**Comment by wbond** [comment] 2016-05-24 13:48
This will be fixed in dev build 3115. It was a bug in Sublime Text proper, and not the syntax.

**Closed by wbond** 2016-05-24 13:48 UTC

**Comment by FichteFoll** [comment] 2016-06-22 11:19
Confirmed fixed, by the way.
