### ISSUE TITLE
[PHP] Wrong folding of heredoc block

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3182] opened 2021-12-30 15:03 UTC
### What happened?

Linux, build 4126

php file
```
<?
//Test heredoc

//id
<<<AB
  function Fake1() {}
AB
  //still heredoc  
  function Fake1b() {}
AB;

//'id'
<<<'BB'
  function Fake2() {}
    BB;  
  function Fake2b() {}
BB;

//"id"  
<<<"DD"
  function Fake3() {}
DD;

function F1() {}
```

1)

folding of the 1st heredoc is bad! from 'AB' until 'AB;' but it must start upper - from `<<<AB`.

2) 

no folding for 3rd heredoc. `<<"DD"`

**Comment by jfcherng** [comment] 2021-12-30 15:22
Parse error: syntax error, unexpected token "function" in aaa.php on line 9

**Comment by Alexey-T** [comment] 2021-12-30 15:27
no! both 'function' words are in the here doc! it's ended by `AB;`

**Comment by keith-hall** [comment] 2021-12-30 15:35
Presumably a duplicate of https://github.com/sublimehq/sublime_text/issues/101

**Comment by jfcherng** [comment] 2021-12-30 15:36
> no! both 'function' words are in the heredoc! it's ended by `AB;`

PHP 8.0.13 doesn't think like that.

**Comment by Alexey-T** [comment] 2021-12-30 15:43
I see the docs tell that closing Id must be with ';'. isn't it?

https://www.phptutorial.net/php-tutorial/php-heredoc/

**Comment by jfcherng** [comment] 2021-12-30 15:53
> I see the docs tell that closing Id must be with `;`. isn't it?

https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

> Prior to PHP 7.3.0, it is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;). 

So, no. A simpler test is that just execute your script and it will tell you whether it's illegal.

**Closed** 2021-12-30 15:57 UTC
Labels: bug
