### ISSUE TITLE
[Typescript] The "definite assignment assertion" in class properties not highlighted properly

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2827] opened 2021-05-23 10:45 UTC
- Sublime Version: 4107
- OS Version: macos

```ts
export class ServerRequest {
  url!: string;
  method?: string;
  proto: string;
}
```

Fails at `url!: string;`. The type is not highlighted as is the case in the lines below.

![Screenshot 2021-05-23 at 12 45 20](https://user-images.githubusercontent.com/153197/119257259-bd5e7380-bbc4-11eb-8a66-39c68e7a46d9.png)

**Comment by Thom1729** [comment] 2021-05-23 15:55
Fixed in the linked PR.

I wonder if I should just move the `?` and `!` modifiers inside the `ts-type-assertion` context for simplicity's sake. It would support the modifiers even in illegal places, but that probably doesn't matter.

**Comment by rchl** [comment] 2021-05-23 16:47
I guess you've seen the Discord discussion about that and the old TS release notes about this feature: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions

It is supposed to be supported in more contexts.

**Comment by rchl** [comment] 2021-05-23 16:52
For example this is also possible:
```ts
let x!: number;
let y!: number;

const r = x! + y!;
```

This looks correct:

![Screenshot 2021-05-23 at 18 52 28](https://user-images.githubusercontent.com/153197/119269442-0845ae80-bbf8-11eb-8d70-d34ff99cd248.png)

But this probably not:

![Screenshot 2021-05-23 at 18 52 51](https://user-images.githubusercontent.com/153197/119269455-14317080-bbf8-11eb-9cfd-fdf8803d7bf9.png)

**Comment by Thom1729** [comment] 2021-05-23 17:29
That looks correct to me. In `let x!: number;`, the `!` is part of the type annotation syntax. In `x! + y!`, it's (basically) a unary postfix operator that asserts that `x` is not null. Reasonable people might disagree about the best scopes for each case, but it's working as intended.

**Comment by rchl** [comment] 2021-05-23 17:30
Sounds good. :)

**Comment by Thom1729** [comment] 2021-05-23 17:33
N.B. The docs do refer to the `let x!: number;` syntax as the “the definite assignment assertion operator”, but this is silly; the `!` there does not behave anything like an operator, syntactically or semantically.

**Closed** 2021-06-19 12:17 UTC
