### ISSUE TITLE
[Python] wrong color in f-string

### ISSUE THREAD

**Issue by sweettyler** [sublimehq/Packages#3461] opened 2022-08-04 23:04 UTC
### What happened?

it's easy to reproduce with the following lines:

    i = 10
    print(f"{i}")
    print(f"{i:2d}")

for the last print line, the curly brackets are displayed in different colors, but they shouldn't.

My preference settings are as follows:
	"color_scheme": "Monokai.sublime-color-scheme",
	"theme": "Adaptive.sublime-theme",
![highlight](https://user-images.githubusercontent.com/49961658/182969517-a02d7af6-20d6-4eee-8081-a97fdae3ca3d.png)

**Comment by michaelblyons** [comment] 2022-08-04 23:24
Duplicate of #3444. Already fixed in master.

**Closed** 2022-08-04 23:25 UTC
Labels: bug
