### ISSUE TITLE
[Ruby] `/ @` breaks syntax highlighting

### ISSUE THREAD

**Issue by apbassi89** [sublimehq/Packages#1136] opened 2017-09-13 16:26 UTC
Just upgraded to version 3.0 (congrats) but noticed it's introducing a syntax highlighting issue with ruby when you have a `/` followed by a `@`:

![image](https://user-images.githubusercontent.com/4567815/30388739-7c31924c-9865-11e7-9f7c-80a3b6304689.png)

Removing either the `/` or the `@` stops the syntax highlighting from breaking.

I've replicated this across multiple OSX machines, with multiple color schemes.

**Comment by michaelblyons** [comment] 2017-09-13 17:44
Duplicate of #923 ?

**Comment by apbassi89** [comment] 2017-09-13 18:32
@michaelblyons Hmm it appears this may be a duplicate, although what's interesting is that this syntax issue did _not_ occur until the latest Sublime Text update for me...

**Comment by randy3k** [comment] 2017-09-14 07:18
I think this and #933 are both caused by the same bug in [try-regex](https://github.com/sublimehq/Packages/blob/a290aa062eb00ad5cfc6d9c454c53fb0a534a913/Ruby/Ruby.sublime-syntax#L1055-L1073).

**Comment by randy3k** [comment] 2017-09-14 16:53
#1142 should fix it

**Closed** 2017-09-15 11:35 UTC

**Comment by augnustin** [comment] 2018-01-09 09:12
When is this going to be available in public release?

Cheers
