### ISSUE TITLE
 [Java] Syntax highlighting fails when defining many variables

### ISSUE THREAD

**Issue by mtminhor** [sublimehq/Packages#1393] opened 2018-01-21 08:37 UTC
When defining many variables in one line, syntax highlighting fails after aproximatly 48 variables.

![screenshot from 2018-01-21 03-22-01](https://user-images.githubusercontent.com/35651991/35192220-e89d1b2a-fe5b-11e7-8ec0-8346b889b42f.png)
![screenshot from 2018-01-21 03-32-56](https://user-images.githubusercontent.com/35651991/35192223-f02863ea-fe5b-11e7-90e5-d9fb593b0483.png)

```java
class Test {
    public Test t1  = new Test(0), t2  = new Test(0), t3  = new Test(0), t4  = new Test(0), t5  = new Test(0), 
                t6  = new Test(0), t7  = new Test(0), t8  = new Test(0), t9  = new Test(0), t10 = new Test(0), 
                t11 = new Test(0), t12 = new Test(0), t13 = new Test(0), t14 = new Test(0), t15 = new Test(0), 
                t16 = new Test(0), t17 = new Test(0), t18 = new Test(0), t19 = new Test(0), t20 = new Test(0), 
                t21 = new Test(0), t22 = new Test(0), t23 = new Test(0), t24 = new Test(0), t25 = new Test(0), 
                t26 = new Test(0), t27 = new Test(0), t28 = new Test(0), t29 = new Test(0), t30 = new Test(0), 
                t31 = new Test(0), t32 = new Test(0), t33 = new Test(0), t34 = new Test(0), t35 = new Test(0), 
                t36 = new Test(0), t37 = new Test(0), t38 = new Test(0), t39 = new Test(0), t40 = new Test(0), 
                t41 = new Test(0), t42 = new Test(0), t43 = new Test(0), t44 = new Test(0), t45 = new Test(0), 
                t46 = new Test(0), t47 = new Test(0), t48 = new Test(0), t49 = new Test(0), t50 = new Test(0); 
    public test = new Test(0);
}
```

**Comment by keith-hall** [comment] 2018-01-21 17:28
I can't seem to reproduce this on build 3156.

**Comment by mtminhor** [comment] 2018-01-21 18:20
I'm running build 3143 under linux

**Comment by FichteFoll** [comment] 2018-01-21 20:36
Can't reproduce on 3156 either. It has most likely been fixed already.

**Comment by jfcherng** [comment] 2018-01-23 02:44
Just a FYI. I have a [script](https://git.io/vNVF2) to update local ST packages with this repo.
You can use it if you are unable to access the dev bulid or just be lazy to update packages by yourself.

**Comment by wbond** [comment] 2018-02-09 20:35
I am not seeing the issue on build 3157, however I am seeing an issue with:

```java
class Test {
    public test = new Test(0);
}
```

@ismell Is this valid code? It seems the `new` is not recognized and then `Test` is seen as a method name.

**Comment by ismell** [comment] 2018-02-09 22:00
It's not valid code as it's missing the type declaration.

**Comment by wbond** [comment] 2018-02-12 16:19
Ok, so the current version of the syntax handles the valid version properly, so I am closing

**Closed by wbond** 2018-02-12 16:19 UTC
