### ISSUE TITLE
[JS] Syntax highlighting 3114

### ISSUE THREAD

**Issue by Qrokqt** [sublimehq/Packages#426] opened 2016-05-23 13:45 UTC
Some variables are now just randomly losing their styles, like the j,k,l in this:

![js_styles](https://cloud.githubusercontent.com/assets/17385843/15472806/ea2b16e2-20ca-11e6-884e-13ef061fc7e1.PNG)

**Comment by FichteFoll** [comment] 2016-05-23 14:05
Please additionally post the code for easier reproduction.

**Comment by keith-hall** [comment] 2016-05-23 14:08
I wonder if it has the same underlying cause as https://github.com/sublimehq/Packages/issues/403

**Comment by Qrokqt** [comment] 2016-05-23 19:57
`
$(function(){
	for(var i in app.bucket.test) {
		if(type == 'poly') {
			for(var j in wkt.components) {
				for(var k in wkt.components[j]) {
					if(Array.isArray(wkt.components[j][k])) {
						for(var l in wkt.components[j][k]) {
							latlngs[j].push(L.latLng(wkt.components[j][k][l].x, wkt.components[j][k][l].y));
						}
					} else {
						latlngs[j].push(L.latLng(wkt.components[j][k].x, wkt.components[j][k].y));
					}
				}
			}
		}
	}
});
`

**Comment by FichteFoll** [comment] 2016-05-24 01:43
works for me

![2016-05-24_03 42 50](https://cloud.githubusercontent.com/assets/931051/15489620/9d939aba-2161-11e6-9307-82b86b1f0149.png)

**Comment by horans** [comment] 2016-05-24 07:44
same problem here:
everything is fine from depth 1 to 7;
in depth 8, arguments lose highlight, but functions work fine;
from depth 9 and on, no more highlight.

![sublime-text-lose-syntax-highlight-with-depth](https://cloud.githubusercontent.com/assets/12060804/15496011/f474d920-21c5-11e6-9e1c-402429bb8618.png)

build: 3114
theme: spacegray

**Comment by wbond** [comment] 2016-05-24 13:48
This will be fixed in dev build 3115. It was a bug in Sublime Text proper, not the syntax.

**Closed by wbond** 2016-05-24 13:48 UTC
