### ISSUE TITLE
[php] Build 3114 syntax highlighting misses keywords

### ISSUE THREAD

**Issue by danielbachhuber** [sublimehq/Packages#410] opened 2016-05-19 11:45 UTC
Here are some keywords that are missing for me:

Build 3114:

![image](https://cloud.githubusercontent.com/assets/36432/15320204/1f362142-1be4-11e6-9531-f22433a0b80c.png)

```
$bits = explode( '/', $assoc_args['name'] );
if ( 2 !== count( $bits ) || empty( $bits[0] ) || empty( $bits[1] ) ) {
	WP_CLI::error( "'{$assoc_args['name']}' is an invalid package name. Package scaffold expects '<author>/<package>'." );
}
```

![image](https://cloud.githubusercontent.com/assets/36432/15320207/24b38632-1be4-11e6-88a1-cb8198576e04.png)

```
<?php

namespace WP_CLI;

use WP_CLI;
use WP_CLI\Process;
use WP_CLI\Utils;
```

Build 3013:

![image](https://cloud.githubusercontent.com/assets/36432/15320279/7ee44326-1be4-11e6-8775-5f8e0153b99f.png)

![image](https://cloud.githubusercontent.com/assets/36432/15320286/874edc1a-1be4-11e6-98d7-4d5f82f4fe33.png)

Originally https://github.com/sublimehq/Packages/issues/389#issuecomment-219763782

**Comment by wbond** [comment] 2016-05-19 17:14
The scopes changes since 3103 since the PHP syntax has been heavily refactored to support new syntax and better handle various constructs.

I've confirmed that `error` in `WP_CLI::error()` is getting the correct scopes. The most specific part is:

```
meta.function-call.static variable.function
```

In the use statements example, the identifiers are getting the correct scopes also. When `use` is encountered, it is unknown if the path ends in a namespace, or a class name. Thus, we don't highlight the final identifier with any specific scope. However, namespace names preceding the  final identifier do have the scope `support.other.namespace`.

I'd be open to ideas on how to handle the ambiguity of scoping namespace/class names in a use statement.

**Comment by wesbos** [comment] 2016-05-30 13:42
Hey - does this mean that my theme should be updated? It's not an error on the highlighter side, but the theme should handle the new scope?

**Comment by wbond** [comment] 2016-06-01 09:50
@wesbos Yes, some of the scope names have changed as we are making things more consistent. If you want to retain the same colors as before for the tokens in the screen shots, I believe your color scheme will need a few tweaks. I believe the advice from @FichteFoll at https://github.com/wesbos/cobalt2/issues/104 should help in getting the colors back to where they were before.

**Comment by wbond** [comment] 2016-07-22 17:36
I don't believe there is anything to be done here, closing.

**Closed by wbond** 2016-07-22 17:36 UTC
Labels: question
