### ISSUE TITLE
error coloring syntah php (shortTag / comments)

### ISSUE THREAD

**Issue by Dardiflette95** [sublimehq/Packages#3574] opened 2022-11-19 09:13 UTC
### Description of the bug

<img width="1043" alt="Capture d’écran 2022-11-19 à 10 06 36" src="https://user-images.githubusercontent.com/59021762/202843626-af305bd3-5ff7-4093-99a9-e640e236d939.png">

### Steps to reproduce

PHP
add comments when using shorttag (<?=$var2print?>)

### Expected behavior

in PHP 
when use comments /**/ and shorttag beetwen color are not good

### Actual behavior

in PHP 
when use comments /**/ and shorttag beetwen color are not good

### Sublime Text build number

4143

### Operating system & version

Mac os 12.4

**Comment by deathaxe** [comment] 2022-11-19 09:44
Duplicate of #3535.

**Closed** 2022-11-19 09:43 UTC
Labels: duplicate
