### ISSUE TITLE
Python Syntax: Python Identifiers containing keywords as substrings confuse highlighter

### ISSUE THREAD

**Issue by dbowring** [sublimehq/Packages#1898] opened 2019-03-13 23:48 UTC
In a dict literal, using a variable that contains a keyword (such as `in`, `yield`, `for`, ...) as a substring in a variable name confuses the syntax highlighter, causing it to mark the comma as an error.

For example:
![python-syntax-issue](https://user-images.githubusercontent.com/2637065/54321763-83899e00-4646-11e9-8de8-ed68c65675a7.png)

```
# For copy/pasting:
{
    "a": something,
    "b": form,  # includes `for`
    "c": defend,  # includes `def`
    "d": fine,  # includes `in`
    "e": asynchronous,  # inclues `async`
}
```

Using build 3200 on linux.

**Comment by michaelblyons** [comment] 2019-03-14 00:00
This is #1896, right?

**Comment by dbowring** [comment] 2019-03-14 01:44
@michaelblyons Yes, that appears to be the same issue.

**Comment by FichteFoll** [comment] 2019-03-14 13:51
Duplicate of #1896. Only the line with "for" causes this behavior, as removing that causes the invalid scopes on the commas to disappear.

![2019-03-14_14-50-43](https://user-images.githubusercontent.com/931051/54362053-90b78480-4668-11e9-9ae9-8d4f3d98538d.png)

**Comment by wbond** [comment] 2019-10-24 17:05
This issue has been solved by a previous commit, hence it is being closed.

**Closed by wbond** 2019-10-24 17:05 UTC
