### ISSUE TITLE
[Python] illegal-assignment incorrectly assigned after type annotation union with |

### ISSUE THREAD

**Issue by kylebebak** [sublimehq/Packages#3521] opened 2022-11-05 15:26 UTC
### What happened?

```py
from __future__ import annotations

a: int | None = 10
```

<img width="616" alt="Screen Shot 2022-11-05 at 9 21 00 AM" src="https://user-images.githubusercontent.com/1524088/200127273-c985d445-c42f-45ea-9526-8c5b9ba6cbb4.png">

This is incorrectly marked with `illegal-assignment` scope.

Build 4140. This is a regression; note that this is not broken in build 4126

**Comment by deathaxe** [comment] 2022-11-05 15:27
Duplicate of #3486

**Closed by deathaxe** 2022-11-05 15:27 UTC
Labels: bug
