### ISSUE TITLE
[Javascript] Syntax highlighting changes (Sunburst)

### ISSUE THREAD

**Issue by eridal** [sublimehq/Packages#142] opened 2016-02-09 20:20 UTC
![problem](https://i.imgur.com/jbC2pcq.png?1)

Here's the example code used:

```js
var foo = {};

foo.key = bar;

var literal = {
  foo: 'foo',
  bar: 'bar',
};

var msg = function () {
  var msg = 'the text';
  console.log(msg);
}

data.baz = function () {
  var obj = {
    some: some('foo')
  };
  console.log(obj.some())
};
```

**Comment by wbond** [comment] 2016-02-09 21:16
This seems to be a duplicate of #141. There is some extended discussion there about the changes and why things look different.

**Closed by wbond** 2016-02-09 21:16 UTC
