### ISSUE TITLE
[Ruby] Syntax highlighting after "/ @" is corrupted

### ISSUE THREAD

**Issue by elDub** [sublimehq/Packages#1150] opened 2017-09-15 21:41 UTC
```ruby
10 + 5 # Good
@var = 5 # Good
10 + @var # Good
10 - @var # Good
10 / @var # Bad
@var * 2 # And everything after is bad too
```

![untitled 2017-09-15 17-41-10](https://user-images.githubusercontent.com/1226748/30504497-12bbb598-9a3d-11e7-8f75-729a015ef0a5.png)

**Comment by michaelblyons** [comment] 2017-09-15 21:43
Duplicate of #1136 and #923

**Comment by michaelblyons** [comment] 2017-09-24 22:22
Is this fixed by #1142?

**Comment by elDub** [comment] 2017-09-25 13:36
I believe it looks good now!

![untitled 2017-09-25 09-35-51](https://user-images.githubusercontent.com/1226748/30811030-f3633c8a-a1d4-11e7-8310-d04a504b2ec7.png)

**Comment by kleinfreund** [comment] 2017-09-25 13:44
@elDub Just noticing, but shouldn’t `/` be highlighted with red like the other operators?

**Comment by elDub** [comment] 2017-09-25 13:47
@kleinfreund: I agree. I was focusing too much on the instance variable. The operator should be red as well.

**Comment by randy3k** [comment] 2017-09-25 16:56
check https://github.com/sublimehq/Packages/pull/1173

**Closed** 2017-10-09 20:21 UTC
