### ISSUE TITLE
[PHP] Unsure what's happening here

### ISSUE THREAD

**Issue by jbrooksuk** [sublimehq/Packages#431] opened 2016-05-25 10:55 UTC
I don't know how to explain what is going on either... Best way is an image.

![image](https://cloud.githubusercontent.com/assets/246103/15537657/9ebc266e-226f-11e6-8084-408c64d1b7e6.png)

**Comment by jbrooksuk** [comment] 2016-05-25 10:56
Is this just a colour scheme thing?

**Comment by wbond** [comment] 2016-05-25 14:11
Can you provide the source file so I can check it out?

It may be related to #403.

**Comment by jbrooksuk** [comment] 2016-05-25 14:13
https://github.com/CachetHQ/Cachet/blob/2.3/app/Http/Routes/DashboardRoutes.php

It's big.

**Comment by wbond** [comment] 2016-05-25 14:16
That file doesn't seem to have the same contents as the screenshot you posted.

**Comment by jbrooksuk** [comment] 2016-05-25 14:18
True, but the contents do the same thing:

![image](https://cloud.githubusercontent.com/assets/246103/15543192/dfcd7830-228b-11e6-9e37-9775918751af.png)

**Comment by wbond** [comment] 2016-05-25 14:19
Ok, I'm compiling an old version to confirm that build 3115 will fix the issue and that it isn't with your color scheme.

**Comment by jbrooksuk** [comment] 2016-05-25 14:20
Thanks :)

**Comment by wbond** [comment] 2016-05-25 14:23
Looks like it is likely the color scheme, although I can't rule out #403 without checking the color scheme. With build 3114 and Monokai:

<img width="760" alt="screen shot 2016-05-25 at 10 20 52 am" src="https://cloud.githubusercontent.com/assets/41734/15543386/afb3c718-2262-11e6-9525-2ff61a7f50dc.png">

**Comment by wbond** [comment] 2016-05-25 14:28
Actually, I can confirm it is #403. Here is the same screenshot from the in-progress version. Notice `Registrar $router` is white in 3114 and highlighted in this:

<img width="745" alt="screen shot 2016-05-25 at 10 27 20 am" src="https://cloud.githubusercontent.com/assets/41734/15543585/70d1452e-2263-11e6-8a45-f25283f033f3.png">

**Comment by wbond** [comment] 2016-05-25 14:28
This will be fixed by dev build 3115.

**Comment by jbrooksuk** [comment] 2016-05-25 14:29
Thanks! :)

**Closed by wbond** 2016-05-25 14:28 UTC

**Comment by jbrooksuk** [comment] 2016-06-02 13:38
Any idea when 3115 will be released @wbond?

I guess this is also the same bug:

![image](https://cloud.githubusercontent.com/assets/246103/15746724/9e37255c-28cf-11e6-8028-07e97e539737.png)

**Comment by wbond** [comment] 2016-06-02 14:18
No, Jon deals with the releases. It is the middle of the night on Thursday in Australia, so I would guess early next week.
