### ISSUE TITLE
[ST3#3114 JavaScript] Goto Definition does not match any variable definitions

### ISSUE THREAD

**Issue by bijoythomas** [sublimehq/Packages#619] opened 2016-09-14 23:19 UTC
let foo = 5;

let bar = () => {};

Goto definition (Cmd-R) does not show 'foo' in its populated list and typing foo does not bring up any matches. 'bar' comes up w/o any issues.

<img width="690" alt="screen shot 2016-09-14 at 6 19 53 pm" src="https://cloud.githubusercontent.com/assets/5385730/18533333/b0e1e604-7aa7-11e6-9a0b-ba12c9b168df.png">

**Comment by FichteFoll** [comment] 2016-09-14 23:27
I'm pretty sure this is intended and consistent with all other languages where only function and class definitions are indexed.

**Comment by bijoythomas** [comment] 2016-09-14 23:36
It's annoying when you use a utility to curry a function and then it disappears from the GoTo list.

`bar = (a, b) => {...}` will work

BUT

`bar = R.curry((a, b) => {...})` now makes bar no longer appear since ST thinks its a variable definition

Is there a way to tell Sublime to look for certain patterns and index them too?

**Comment by wbond** [comment] 2016-09-15 00:13
No, there isn't a "simple" way to configure this. You would have to write a syntax to ensure there is a specific scope for the patterns you want to index. Then you can configure via `.tmPreferences` which scopes to include in the index.

The area that we are most inconsistent right now is in indexing "constants".

**Comment by bijoythomas** [comment] 2016-09-15 00:59
I guess in the meantime I can do something like:

let someFunc = R.curry(function someFunc(args) {})

Not ideal but will serve the purpose.

Is there an example of doing what you mentioned regarding the patterns and `.tmPreferences` configuration?

**Comment by wbond** [comment] 2016-09-21 00:13
@bijoythomas 

Here is an example of setting the scope for a token: https://github.com/sublimehq/Packages/blob/master/PHP/PHP%20Source.sublime-syntax#L54-L57

Here is adding it to the symbol list: https://github.com/sublimehq/Packages/blob/master/PHP/Symbol%20List.tmPreferences#L6-L14

**Comment by wbond** [comment] 2016-09-23 14:58
I'm going to close this for now since it works as intended and consistently with other syntaxes.

The idea of adding functionality to deal with allowing jumping to variable and parameter definitions is currently open (in one form) at https://github.com/SublimeTextIssues/Core/issues/1397.

**Closed by wbond** 2016-09-23 14:58 UTC
Labels: question
