### ISSUE TITLE
[HTML] Doesn't handle indentation for "comment selectors"

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#760] opened 2016-12-26 18:35 UTC
I don't exactly know how these are called, but I was made aware of this issue.

1) 
```html
<!DOCTYPE html>
<html>
<head>
    <!--[if lt IE 9]>
        <script src=""></script>
    <![endif]-->
</head>
<body>

</body>
</html>
```

2) Run *Reindent* command.

3)
```html
<!DOCTYPE html>
<html>
<head>
    <!--[if lt IE 9]>
        <script src=""></script>
        <![endif]-->
    </head>
    <body>

    </body>
    </html>
```

Similarly, indentation is not increased when pressing <kbd>Enter</kbd> in the `<!--[if lt IE 9]>` line.

**Comment by keith-hall** [comment] 2016-12-26 18:42
> Similarly, indentation is not increased when pressing <kbd>Enter</kbd> in the `<!--[if lt IE 9]>` line.

is that not because HTML uses `batch` increase/decrease indent patterns? i.e. the same with just pressing <kbd>Enter</kbd> after `<!--`?

**Comment by keith-hall** [comment] 2017-03-24 13:07
I've just included a fix for this in https://github.com/sublimehq/Packages/pull/841

**Comment by wbond** [comment] 2017-04-05 08:47
I can confirm this is fixed in the latest version of the HTML package

**Closed by wbond** 2017-04-05 08:47 UTC
